CREATE DATABASE IF NOT EXISTS bbce;
CREATE DATABASE IF NOT EXISTS carteira;
CREATE DATABASE IF NOT EXISTS db_book_gd;
CREATE DATABASE IF NOT EXISTS db_carga_consumidor;
CREATE DATABASE IF NOT EXISTS db_config;
CREATE DATABASE IF NOT EXISTS db_decks;
CREATE DATABASE IF NOT EXISTS db_meteorologia;
CREATE DATABASE IF NOT EXISTS db_ons;
CREATE DATABASE IF NOT EXISTS db_pluvia;
CREATE DATABASE IF NOT EXISTS db_rodadas;
CREATE DATABASE IF NOT EXISTS db_tmp;
CREATE DATABASE IF NOT EXISTS climenergy;
CREATE DATABASE IF NOT EXISTS db_ons_dados_abertos;
CREATE DATABASE IF NOT EXISTS airflow;


CREATE USER 'climenergy'@'%' IDENTIFIED BY 'climeserver';
GRANT Create role ON *.* TO 'climenergy'@'%';
GRANT Create user ON *.* TO 'climenergy'@'%';
GRANT Drop role ON *.* TO 'climenergy'@'%';
GRANT Event ON *.* TO 'climenergy'@'%';
GRANT File ON *.* TO 'climenergy'@'%';
GRANT Process ON *.* TO 'climenergy'@'%';
GRANT Reload ON *.* TO 'climenergy'@'%';
GRANT Replication client ON *.* TO 'climenergy'@'%';
GRANT Replication slave ON *.* TO 'climenergy'@'%';
GRANT Show databases ON *.* TO 'climenergy'@'%';
GRANT Shutdown ON *.* TO 'climenergy'@'%';
GRANT Super ON *.* TO 'climenergy'@'%';
GRANT Create tablespace ON *.* TO 'climenergy'@'%';
GRANT Usage ON *.* TO 'climenergy'@'%';
GRANT AUDIT_ABORT_EXEMPT ON *.* TO 'climenergy'@'%';
GRANT FIREWALL_EXEMPT ON *.* TO 'climenergy'@'%';
GRANT OPTIMIZE_LOCAL_TABLE ON *.* TO 'climenergy'@'%';
GRANT ALLOW_NONEXISTENT_DEFINER ON *.* TO 'climenergy'@'%';
GRANT SET_ANY_DEFINER ON *.* TO 'climenergy'@'%';
GRANT SENSITIVE_VARIABLES_OBSERVER ON *.* TO 'climenergy'@'%';
GRANT AUTHENTICATION_POLICY_ADMIN ON *.* TO 'climenergy'@'%';
GRANT GROUP_REPLICATION_STREAM ON *.* TO 'climenergy'@'%';
GRANT FLUSH_PRIVILEGES ON *.* TO 'climenergy'@'%';
GRANT XA_RECOVER_ADMIN ON *.* TO 'climenergy'@'%';
GRANT CONNECTION_ADMIN ON *.* TO 'climenergy'@'%';
GRANT CLONE_ADMIN ON *.* TO 'climenergy'@'%';
GRANT ENCRYPTION_KEY_ADMIN ON *.* TO 'climenergy'@'%';
GRANT INNODB_REDO_LOG_ARCHIVE ON *.* TO 'climenergy'@'%';
GRANT SESSION_VARIABLES_ADMIN ON *.* TO 'climenergy'@'%';
GRANT APPLICATION_PASSWORD_ADMIN ON *.* TO 'climenergy'@'%';
GRANT REPLICATION_SLAVE_ADMIN ON *.* TO 'climenergy'@'%';
GRANT BACKUP_ADMIN ON *.* TO 'climenergy'@'%';
GRANT GROUP_REPLICATION_ADMIN ON *.* TO 'climenergy'@'%';
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO 'climenergy'@'%';
GRANT BINLOG_ADMIN ON *.* TO 'climenergy'@'%';
GRANT PERSIST_RO_VARIABLES_ADMIN ON *.* TO 'climenergy'@'%';
GRANT TRANSACTION_GTID_TAG ON *.* TO 'climenergy'@'%';
GRANT PASSWORDLESS_USER_ADMIN ON *.* TO 'climenergy'@'%';
GRANT ROLE_ADMIN ON *.* TO 'climenergy'@'%';
GRANT INNODB_REDO_LOG_ENABLE ON *.* TO 'climenergy'@'%';
GRANT RESOURCE_GROUP_USER ON *.* TO 'climenergy'@'%';
GRANT BINLOG_ENCRYPTION_ADMIN ON *.* TO 'climenergy'@'%';
GRANT SERVICE_CONNECTION_ADMIN ON *.* TO 'climenergy'@'%';
GRANT SHOW_ROUTINE ON *.* TO 'climenergy'@'%';
GRANT RESOURCE_GROUP_ADMIN ON *.* TO 'climenergy'@'%';
GRANT SYSTEM_USER ON *.* TO 'climenergy'@'%';
GRANT TABLE_ENCRYPTION_ADMIN ON *.* TO 'climenergy'@'%';
GRANT TELEMETRY_LOG_ADMIN ON *.* TO 'climenergy'@'%';
GRANT FLUSH_STATUS ON *.* TO 'climenergy'@'%';
GRANT REPLICATION_APPLIER ON *.* TO 'climenergy'@'%';
GRANT FLUSH_OPTIMIZER_COSTS ON *.* TO 'climenergy'@'%';
GRANT AUDIT_ADMIN ON *.* TO 'climenergy'@'%';
GRANT FLUSH_USER_RESOURCES ON *.* TO 'climenergy'@'%';
GRANT FLUSH_TABLES ON *.* TO 'climenergy'@'%';
GRANT Grant option ON *.* TO 'climenergy'@'%';

GRANT ALL PRIVILEGES ON *.* TO 'climenergy'@'%' WITH GRANT OPTION;